### ISSUE TITLE
Document clarification

### ISSUE THREAD

**Issue by neginbasiri** [HubSpot/cms-react-boilerplate#15]
Hi,

In the docs for running the app, it's mentioned "Create a page from default theme, or any drag-and-drop (dnd_area) enabled template in your portal, and add the app (label: React app boilerplate) module."
It's not clear, can you please provide an example to make it clearer?

**Comment by oscarsidebo** [comment]
How was this resolved?

**Comment by hrdunn** [comment]
@neginbasiri how was this resolved? I attempted to add a page but it is unclear from the docs what is supposed to be done next. New to hubspot CMS but not react.
