### ISSUE TITLE
Instruct on what version of node to use

### ISSUE THREAD

**Issue by dwootton** [HubSpot/cms-react-boilerplate#32]
I ran into an issue via npm install that would exit via "/Users/<username>/.node-gyp/16.13.0/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?"

I tried this with different versions of node and it seems the issue may occur when used with v17.0.1. 

I still ran into other problems, but this should be addressed in the getting started guide because the Hubspot website CLI says any version of node 10+ will suffice, which doesn't seem to be true. 

v16.13.1 seemed to begin the install, but then I ran into a missing hubspot webpack cms plugins issue 

For reference to anyone else struggling with this: https://itnext.io/nvm-the-easiest-way-to-switch-node-js-environments-on-your-machine-in-a-flash-17babb7d5f1b?gi=9baa4b77125e

**Comment by krittiyaclark** [comment]
> I ran into an issue via npm install that would exit via "/Users//.node-gyp/16.13.0/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?"
> 
> I tried this with different versions of node and it seems the issue may occur when used with v17.0.1.
> 
> I still ran into other problems, but this should be addressed in the getting started guide because the Hubspot website CLI says any version of node 10+ will suffice, which doesn't seem to be true.
> 
> v16.13.1 seemed to begin the install, but then I ran into a missing hubspot webpack cms plugins issue
> 
> For reference to anyone else struggling with this: https://itnext.io/nvm-the-easiest-way-to-switch-node-js-environments-on-your-machine-in-a-flash-17babb7d5f1b?gi=9baa4b77125e

I have a same issue so I built a React app with Webpack and an React app was running.

**Comment by timmfin** [comment]
Closing the issue because it was (finally) fixed by moving from node-sass to (dart) sass in https://github.com/HubSpot/cms-react-boilerplate/pull/44. I also verified that you can install and build this project with node 16 (and the associated lint automation runs on node 16).
